name: Update generated parser

on:
  schedule:
    - cron: "0 0 1 * *" # every month
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          cache: npm
          node-version: 20
      - uses: tree-sitter/parser-update-action@v1.1
